### ISSUE TITLE
HopHud with Keepers

### ISSUE THREAD

**Issue by TrystanBartel** [segabl/pd2-hophud#1]
I'm getting the following error while using the hud with keepers. It shows the error in the name of the Joker.

ERROR: hud_hophud_unit_type_npc

Instead of showing, for example: Joker "Player's Heavy Swat" in green, it shows like the image.

[Screenshot](https://i.ibb.co/6NSxvRB/error.png)

Usually happens on second joker, offline test.
Online happens with my second joker and other players jokers.

**Comment by segabl** [comment]
Hmm, do you have the most recent version of HopLib and HopHUD?

**Comment by TrystanBartel** [comment]
Yes, both on last version.

**Comment by segabl** [comment]
hmm it should not use unit_type_npc, any other ai related mods active?

**Comment by TrystanBartel** [comment]
Keepers, Monkeepers, Useful Bots and Iter.

I'll do some tests removing other mods.

**Comment by TrystanBartel** [comment]
I think the problem is with the mod "Less Confusing Intimidated Outlines", clientside version.
Apparently it changes something while outlining the intimidated cop.
Removing the mod seems to have fixed the problem.

Sorry to bother and thanks for your mods and your time.

**Comment by TrystanBartel** [comment]
Just to add,

A workaround is to add "hud_hophud_unit_type_npc" : "Joker", to loc/english.txt
It'll remove the error but won't show players name. Not a fix.

For example:
Right: Joker Player's Heavy Swat
Workaround: Joker Heavy Swat

**Comment by segabl** [comment]
Yeah looks like that mod prevents HopLib from knowing that the unit has been converted by a player. I've had multiple reports on incompatibilities in relation with that mod when it comes to converted enemies in general, so that's an issue with that mod's code.
