### ISSUE TITLE
When I try to load a game it crashes

### ISSUE THREAD

**Issue by lncognito-Cat** [segabl/pd2-hophud#2]
In the [crash.txt](https://github.com/segabl/pd2-hophud/files/8931814/crash.txt) for payday 2 it shows this:

Application has crashed: C++ exception
mods/pd2-hophud-master/lua/hudteammate.lua:128: attempt to index field '_downs_bg' (a nil value)

SCRIPT STACK

set_teammate_name_panel() @mods/pd2-hophud-master/mod.lua:205
func() @mods/pd2-hophud-master/lua/hudmanager.lua:26
reset_player_hpbar() @mods/base/req/core/Hooks.lua:294
original() lib/managers/criminalsmanager.lua:309
add_character() @mods/base/req/core/Hooks.lua:288
set_unit() lib/network/base/networkpeer.lua:2391
spawn_unit() lib/network/base/networkpeer.lua:2280
spawn_players() lib/network/base/basenetworksession.lua:1513
Run() lib/states/ingamewaitingforplayers.lua:293
update() @mods/PocoHUD3/poco/../poco/Hud3.lua:2828
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
original() lib/setups/setup.lua:913
update() @mods/base/req/core/Hooks.lua:288

update() lib/setups/gamesetup.lua:764
_update() lib/setups/networkgamesetup.lua:21
update() @mods\PocoHUD3\poco\common.lua:310
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
                         ntdll  (???)     RtlAnsiStringToUnicodeString                        
                         ntdll  (???)     RtlAllocateHeap                                     
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.123.108
	CPU : 12th Gen Intel(R) Core(TM) i7-12700H (10 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3050 Laptop GPU / nvldumd.dll[31.0.15.1640]
	Language : english
	Memory :     16004MB 996KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (Plantronics Blackwire 5220 Series))

**Comment by segabl** [comment]
I'm gonna assume this is an incompatibility with pocohud, can you try without that to see if that fixes it?

**Comment by lncognito-Cat** [comment]
Alright

**Comment by lncognito-Cat** [comment]
It still crashes when I load a game.

the [crash.txt](https://github.com/segabl/pd2-hophud/files/8934080/crash.txt) shows:

Application has crashed: C++ exception
mods/pd2-hophud-master/lua/hudteammate.lua:128: attempt to index field '_downs_bg' (a nil value)



SCRIPT STACK

set_teammate_name_panel() @mods/pd2-hophud-master/mod.lua:205
func() @mods/pd2-hophud-master/lua/hudmanager.lua:26
reset_player_hpbar() @mods/base/req/core/Hooks.lua:294
original() lib/managers/criminalsmanager.lua:309
add_character() @mods/base/req/core/Hooks.lua:288
set_unit() lib/network/base/networkpeer.lua:2391
spawn_unit() lib/network/base/networkpeer.lua:2280
spawn_players() lib/network/base/basenetworksession.lua:1513
update() lib/states/ingamewaitingforplayers.lua:293
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
original() lib/setups/setup.lua:913
update() @mods/base/req/core/Hooks.lua:288
update() lib/setups/gamesetup.lua:764
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
                         ntdll  (???)     RtlAnsiStringToUnicodeString                        
                         ntdll  (???)     RtlAllocateHeap                                     
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlInitializeCriticalSectionEx                      
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlAllocateHeap                                     
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlReAllocateHeap                                   
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.123.108
	CPU : 12th Gen Intel(R) Core(TM) i7-12700H (10 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3050 Laptop GPU / nvldumd.dll[31.0.15.1640]
	Language : english
	Memory :     16004MB 996KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headset Earphone (Plantronics Blackwire 5220 Series))

**Comment by segabl** [comment]
Do you have any other HUD related mods?

**Comment by lncognito-Cat** [comment]
I have PTH:Reborn

**Comment by lncognito-Cat** [comment]
https://modworkshop.net/mod/19900 (PDTH:Reborn)

**Comment by lncognito-Cat** [comment]
I uninstalled the hud and it works perfectly fine (PDTH:Reborn)

**Comment by lncognito-Cat** [comment]
Could you please make it compatible with it

**Comment by lncognito-Cat** [comment]
It works well with POCOHUD 3
